// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 startTime = 1;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>int64 startTime = 1;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>string eventTypeId = 2;</code>
   * @return Whether the eventTypeId field is set.
   */
  boolean hasEventTypeId();
  /**
   * <code>string eventTypeId = 2;</code>
   * @return The eventTypeId.
   */
  java.lang.String getEventTypeId();
  /**
   * <code>string eventTypeId = 2;</code>
   * @return The bytes for eventTypeId.
   */
  com.google.protobuf.ByteString
      getEventTypeIdBytes();

  /**
   * <code>repeated .protobuf.run.TokenMove removeTokens = 3;</code>
   */
  java.util.List<protobuf.run.TokenMove> 
      getRemoveTokensList();
  /**
   * <code>repeated .protobuf.run.TokenMove removeTokens = 3;</code>
   */
  protobuf.run.TokenMove getRemoveTokens(int index);
  /**
   * <code>repeated .protobuf.run.TokenMove removeTokens = 3;</code>
   */
  int getRemoveTokensCount();
  /**
   * <code>repeated .protobuf.run.TokenMove removeTokens = 3;</code>
   */
  java.util.List<? extends protobuf.run.TokenMoveOrBuilder> 
      getRemoveTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.run.TokenMove removeTokens = 3;</code>
   */
  protobuf.run.TokenMoveOrBuilder getRemoveTokensOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.run.TokenMove addTokens = 4;</code>
   */
  java.util.List<protobuf.run.TokenMove> 
      getAddTokensList();
  /**
   * <code>repeated .protobuf.run.TokenMove addTokens = 4;</code>
   */
  protobuf.run.TokenMove getAddTokens(int index);
  /**
   * <code>repeated .protobuf.run.TokenMove addTokens = 4;</code>
   */
  int getAddTokensCount();
  /**
   * <code>repeated .protobuf.run.TokenMove addTokens = 4;</code>
   */
  java.util.List<? extends protobuf.run.TokenMoveOrBuilder> 
      getAddTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.run.TokenMove addTokens = 4;</code>
   */
  protobuf.run.TokenMoveOrBuilder getAddTokensOrBuilder(
      int index);

  /**
   * <code>string viaTransitionId = 5;</code>
   * @return Whether the viaTransitionId field is set.
   */
  boolean hasViaTransitionId();
  /**
   * <code>string viaTransitionId = 5;</code>
   * @return The viaTransitionId.
   */
  java.lang.String getViaTransitionId();
  /**
   * <code>string viaTransitionId = 5;</code>
   * @return The bytes for viaTransitionId.
   */
  com.google.protobuf.ByteString
      getViaTransitionIdBytes();

  /**
   * <code>.protobuf.run.Color color = 6;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.protobuf.run.Color color = 6;</code>
   * @return The color.
   */
  protobuf.run.Color getColor();
  /**
   * <code>.protobuf.run.Color color = 6;</code>
   */
  protobuf.run.ColorOrBuilder getColorOrBuilder();
}
