// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface ActiveIntervalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.ActiveInterval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 startTime = 1;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>int64 startTime = 1;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 endTime = 2;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>int64 endTime = 2;</code>
   * @return The endTime.
   */
  long getEndTime();
}
