// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

/**
 * Protobuf type {@code protobuf.run.Arc}
 */
public final class Arc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.run.Arc)
    ArcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Arc.newBuilder() to construct.
  private Arc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Arc() {
    id_ = "";
    name_ = "";
    sourceId_ = "";
    targetId_ = "";
    coordinates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Arc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Arc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            targetId_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              coordinates_ = new java.util.ArrayList<protobuf.run.Coordinate>();
              mutable_bitField0_ |= 0x00000002;
            }
            coordinates_.add(
                input.readMessage(protobuf.run.Coordinate.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.run.RunOuterClass.internal_static_protobuf_run_Arc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.run.RunOuterClass.internal_static_protobuf_run_Arc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.run.Arc.class, protobuf.run.Arc.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEID_FIELD_NUMBER = 3;
  private volatile java.lang.Object sourceId_;
  /**
   * <code>string sourceId = 3;</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public java.lang.String getSourceId() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceId_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceId = 3;</code>
   * @return The bytes for sourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIdBytes() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGETID_FIELD_NUMBER = 4;
  private volatile java.lang.Object targetId_;
  /**
   * <code>string targetId = 4;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public java.lang.String getTargetId() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetId_ = s;
      return s;
    }
  }
  /**
   * <code>string targetId = 4;</code>
   * @return The bytes for targetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetIdBytes() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COORDINATES_FIELD_NUMBER = 5;
  private java.util.List<protobuf.run.Coordinate> coordinates_;
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.run.Coordinate> getCoordinatesList() {
    return coordinates_;
  }
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.run.CoordinateOrBuilder> 
      getCoordinatesOrBuilderList() {
    return coordinates_;
  }
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  @java.lang.Override
  public int getCoordinatesCount() {
    return coordinates_.size();
  }
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  @java.lang.Override
  public protobuf.run.Coordinate getCoordinates(int index) {
    return coordinates_.get(index);
  }
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  @java.lang.Override
  public protobuf.run.CoordinateOrBuilder getCoordinatesOrBuilder(
      int index) {
    return coordinates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getSourceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceId_);
    }
    if (!getTargetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetId_);
    }
    for (int i = 0; i < coordinates_.size(); i++) {
      output.writeMessage(5, coordinates_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getSourceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceId_);
    }
    if (!getTargetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, targetId_);
    }
    for (int i = 0; i < coordinates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, coordinates_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.run.Arc)) {
      return super.equals(obj);
    }
    protobuf.run.Arc other = (protobuf.run.Arc) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!getSourceId()
        .equals(other.getSourceId())) return false;
    if (!getTargetId()
        .equals(other.getTargetId())) return false;
    if (!getCoordinatesList()
        .equals(other.getCoordinatesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceId().hashCode();
    hash = (37 * hash) + TARGETID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId().hashCode();
    if (getCoordinatesCount() > 0) {
      hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinatesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.run.Arc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Arc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Arc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Arc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Arc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Arc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Arc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.run.Arc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.run.Arc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.run.Arc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.run.Arc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.run.Arc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.run.Arc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.run.Arc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.run.Arc)
      protobuf.run.ArcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Arc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Arc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.run.Arc.class, protobuf.run.Arc.Builder.class);
    }

    // Construct using protobuf.run.Arc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoordinatesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sourceId_ = "";

      targetId_ = "";

      if (coordinatesBuilder_ == null) {
        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        coordinatesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Arc_descriptor;
    }

    @java.lang.Override
    public protobuf.run.Arc getDefaultInstanceForType() {
      return protobuf.run.Arc.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.run.Arc build() {
      protobuf.run.Arc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.run.Arc buildPartial() {
      protobuf.run.Arc result = new protobuf.run.Arc(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      result.sourceId_ = sourceId_;
      result.targetId_ = targetId_;
      if (coordinatesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.coordinates_ = coordinates_;
      } else {
        result.coordinates_ = coordinatesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.run.Arc) {
        return mergeFrom((protobuf.run.Arc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.run.Arc other) {
      if (other == protobuf.run.Arc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (!other.getSourceId().isEmpty()) {
        sourceId_ = other.sourceId_;
        onChanged();
      }
      if (!other.getTargetId().isEmpty()) {
        targetId_ = other.targetId_;
        onChanged();
      }
      if (coordinatesBuilder_ == null) {
        if (!other.coordinates_.isEmpty()) {
          if (coordinates_.isEmpty()) {
            coordinates_ = other.coordinates_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCoordinatesIsMutable();
            coordinates_.addAll(other.coordinates_);
          }
          onChanged();
        }
      } else {
        if (!other.coordinates_.isEmpty()) {
          if (coordinatesBuilder_.isEmpty()) {
            coordinatesBuilder_.dispose();
            coordinatesBuilder_ = null;
            coordinates_ = other.coordinates_;
            bitField0_ = (bitField0_ & ~0x00000002);
            coordinatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoordinatesFieldBuilder() : null;
          } else {
            coordinatesBuilder_.addAllMessages(other.coordinates_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.run.Arc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.run.Arc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceId_ = "";
    /**
     * <code>string sourceId = 3;</code>
     * @return The sourceId.
     */
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceId = 3;</code>
     * @return The bytes for sourceId.
     */
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceId = 3;</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      
      sourceId_ = getDefaultInstance().getSourceId();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceId = 3;</code>
     * @param value The bytes for sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object targetId_ = "";
    /**
     * <code>string targetId = 4;</code>
     * @return The targetId.
     */
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string targetId = 4;</code>
     * @return The bytes for targetId.
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string targetId = 4;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string targetId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      
      targetId_ = getDefaultInstance().getTargetId();
      onChanged();
      return this;
    }
    /**
     * <code>string targetId = 4;</code>
     * @param value The bytes for targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<protobuf.run.Coordinate> coordinates_ =
      java.util.Collections.emptyList();
    private void ensureCoordinatesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        coordinates_ = new java.util.ArrayList<protobuf.run.Coordinate>(coordinates_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.run.Coordinate, protobuf.run.Coordinate.Builder, protobuf.run.CoordinateOrBuilder> coordinatesBuilder_;

    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public java.util.List<protobuf.run.Coordinate> getCoordinatesList() {
      if (coordinatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coordinates_);
      } else {
        return coordinatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public int getCoordinatesCount() {
      if (coordinatesBuilder_ == null) {
        return coordinates_.size();
      } else {
        return coordinatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public protobuf.run.Coordinate getCoordinates(int index) {
      if (coordinatesBuilder_ == null) {
        return coordinates_.get(index);
      } else {
        return coordinatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder setCoordinates(
        int index, protobuf.run.Coordinate value) {
      if (coordinatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinatesIsMutable();
        coordinates_.set(index, value);
        onChanged();
      } else {
        coordinatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder setCoordinates(
        int index, protobuf.run.Coordinate.Builder builderForValue) {
      if (coordinatesBuilder_ == null) {
        ensureCoordinatesIsMutable();
        coordinates_.set(index, builderForValue.build());
        onChanged();
      } else {
        coordinatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder addCoordinates(protobuf.run.Coordinate value) {
      if (coordinatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinatesIsMutable();
        coordinates_.add(value);
        onChanged();
      } else {
        coordinatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder addCoordinates(
        int index, protobuf.run.Coordinate value) {
      if (coordinatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinatesIsMutable();
        coordinates_.add(index, value);
        onChanged();
      } else {
        coordinatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder addCoordinates(
        protobuf.run.Coordinate.Builder builderForValue) {
      if (coordinatesBuilder_ == null) {
        ensureCoordinatesIsMutable();
        coordinates_.add(builderForValue.build());
        onChanged();
      } else {
        coordinatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder addCoordinates(
        int index, protobuf.run.Coordinate.Builder builderForValue) {
      if (coordinatesBuilder_ == null) {
        ensureCoordinatesIsMutable();
        coordinates_.add(index, builderForValue.build());
        onChanged();
      } else {
        coordinatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder addAllCoordinates(
        java.lang.Iterable<? extends protobuf.run.Coordinate> values) {
      if (coordinatesBuilder_ == null) {
        ensureCoordinatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coordinates_);
        onChanged();
      } else {
        coordinatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder clearCoordinates() {
      if (coordinatesBuilder_ == null) {
        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        coordinatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public Builder removeCoordinates(int index) {
      if (coordinatesBuilder_ == null) {
        ensureCoordinatesIsMutable();
        coordinates_.remove(index);
        onChanged();
      } else {
        coordinatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public protobuf.run.Coordinate.Builder getCoordinatesBuilder(
        int index) {
      return getCoordinatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public protobuf.run.CoordinateOrBuilder getCoordinatesOrBuilder(
        int index) {
      if (coordinatesBuilder_ == null) {
        return coordinates_.get(index);  } else {
        return coordinatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public java.util.List<? extends protobuf.run.CoordinateOrBuilder> 
         getCoordinatesOrBuilderList() {
      if (coordinatesBuilder_ != null) {
        return coordinatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coordinates_);
      }
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public protobuf.run.Coordinate.Builder addCoordinatesBuilder() {
      return getCoordinatesFieldBuilder().addBuilder(
          protobuf.run.Coordinate.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public protobuf.run.Coordinate.Builder addCoordinatesBuilder(
        int index) {
      return getCoordinatesFieldBuilder().addBuilder(
          index, protobuf.run.Coordinate.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
     */
    public java.util.List<protobuf.run.Coordinate.Builder> 
         getCoordinatesBuilderList() {
      return getCoordinatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.run.Coordinate, protobuf.run.Coordinate.Builder, protobuf.run.CoordinateOrBuilder> 
        getCoordinatesFieldBuilder() {
      if (coordinatesBuilder_ == null) {
        coordinatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.run.Coordinate, protobuf.run.Coordinate.Builder, protobuf.run.CoordinateOrBuilder>(
                coordinates_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        coordinates_ = null;
      }
      return coordinatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.run.Arc)
  }

  // @@protoc_insertion_point(class_scope:protobuf.run.Arc)
  private static final protobuf.run.Arc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.run.Arc();
  }

  public static protobuf.run.Arc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Arc>
      PARSER = new com.google.protobuf.AbstractParser<Arc>() {
    @java.lang.Override
    public Arc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Arc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Arc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Arc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.run.Arc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

