// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface ArcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Arc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sourceId = 3;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string sourceId = 3;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string targetId = 4;</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <code>string targetId = 4;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  java.util.List<protobuf.run.Coordinate> 
      getCoordinatesList();
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  protobuf.run.Coordinate getCoordinates(int index);
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  int getCoordinatesCount();
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  java.util.List<? extends protobuf.run.CoordinateOrBuilder> 
      getCoordinatesOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Coordinate coordinates = 5;</code>
   */
  protobuf.run.CoordinateOrBuilder getCoordinatesOrBuilder(
      int index);
}
