// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

/**
 * Protobuf type {@code protobuf.run.Color}
 */
public final class Color extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.run.Color)
    ColorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Color.newBuilder() to construct.
  private Color(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Color() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Color();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Color(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            r_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            g_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            b_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.run.RunOuterClass.internal_static_protobuf_run_Color_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.run.RunOuterClass.internal_static_protobuf_run_Color_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.run.Color.class, protobuf.run.Color.Builder.class);
  }

  private int bitField0_;
  public static final int R_FIELD_NUMBER = 1;
  private int r_;
  /**
   * <code>int32 r = 1;</code>
   * @return Whether the r field is set.
   */
  @java.lang.Override
  public boolean hasR() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>int32 r = 1;</code>
   * @return The r.
   */
  @java.lang.Override
  public int getR() {
    return r_;
  }

  public static final int G_FIELD_NUMBER = 2;
  private int g_;
  /**
   * <code>int32 g = 2;</code>
   * @return Whether the g field is set.
   */
  @java.lang.Override
  public boolean hasG() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>int32 g = 2;</code>
   * @return The g.
   */
  @java.lang.Override
  public int getG() {
    return g_;
  }

  public static final int B_FIELD_NUMBER = 3;
  private int b_;
  /**
   * <code>int32 b = 3;</code>
   * @return Whether the b field is set.
   */
  @java.lang.Override
  public boolean hasB() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>int32 b = 3;</code>
   * @return The b.
   */
  @java.lang.Override
  public int getB() {
    return b_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, r_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, g_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, b_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, r_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, g_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, b_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.run.Color)) {
      return super.equals(obj);
    }
    protobuf.run.Color other = (protobuf.run.Color) obj;

    if (hasR() != other.hasR()) return false;
    if (hasR()) {
      if (getR()
          != other.getR()) return false;
    }
    if (hasG() != other.hasG()) return false;
    if (hasG()) {
      if (getG()
          != other.getG()) return false;
    }
    if (hasB() != other.hasB()) return false;
    if (hasB()) {
      if (getB()
          != other.getB()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasR()) {
      hash = (37 * hash) + R_FIELD_NUMBER;
      hash = (53 * hash) + getR();
    }
    if (hasG()) {
      hash = (37 * hash) + G_FIELD_NUMBER;
      hash = (53 * hash) + getG();
    }
    if (hasB()) {
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.run.Color parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Color parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Color parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Color parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Color parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.run.Color parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.run.Color parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.run.Color parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.run.Color parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.run.Color parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.run.Color parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.run.Color parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.run.Color prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.run.Color}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.run.Color)
      protobuf.run.ColorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Color_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Color_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.run.Color.class, protobuf.run.Color.Builder.class);
    }

    // Construct using protobuf.run.Color.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      r_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      g_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      b_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.run.RunOuterClass.internal_static_protobuf_run_Color_descriptor;
    }

    @java.lang.Override
    public protobuf.run.Color getDefaultInstanceForType() {
      return protobuf.run.Color.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.run.Color build() {
      protobuf.run.Color result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.run.Color buildPartial() {
      protobuf.run.Color result = new protobuf.run.Color(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.r_ = r_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.g_ = g_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.b_ = b_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.run.Color) {
        return mergeFrom((protobuf.run.Color)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.run.Color other) {
      if (other == protobuf.run.Color.getDefaultInstance()) return this;
      if (other.hasR()) {
        setR(other.getR());
      }
      if (other.hasG()) {
        setG(other.getG());
      }
      if (other.hasB()) {
        setB(other.getB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.run.Color parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.run.Color) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int r_ ;
    /**
     * <code>int32 r = 1;</code>
     * @return Whether the r field is set.
     */
    @java.lang.Override
    public boolean hasR() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>int32 r = 1;</code>
     * @return The r.
     */
    @java.lang.Override
    public int getR() {
      return r_;
    }
    /**
     * <code>int32 r = 1;</code>
     * @param value The r to set.
     * @return This builder for chaining.
     */
    public Builder setR(int value) {
      bitField0_ |= 0x00000001;
      r_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 r = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearR() {
      bitField0_ = (bitField0_ & ~0x00000001);
      r_ = 0;
      onChanged();
      return this;
    }

    private int g_ ;
    /**
     * <code>int32 g = 2;</code>
     * @return Whether the g field is set.
     */
    @java.lang.Override
    public boolean hasG() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int32 g = 2;</code>
     * @return The g.
     */
    @java.lang.Override
    public int getG() {
      return g_;
    }
    /**
     * <code>int32 g = 2;</code>
     * @param value The g to set.
     * @return This builder for chaining.
     */
    public Builder setG(int value) {
      bitField0_ |= 0x00000002;
      g_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 g = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearG() {
      bitField0_ = (bitField0_ & ~0x00000002);
      g_ = 0;
      onChanged();
      return this;
    }

    private int b_ ;
    /**
     * <code>int32 b = 3;</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>int32 b = 3;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }
    /**
     * <code>int32 b = 3;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(int value) {
      bitField0_ |= 0x00000004;
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 b = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      bitField0_ = (bitField0_ & ~0x00000004);
      b_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.run.Color)
  }

  // @@protoc_insertion_point(class_scope:protobuf.run.Color)
  private static final protobuf.run.Color DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.run.Color();
  }

  public static protobuf.run.Color getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Color>
      PARSER = new com.google.protobuf.AbstractParser<Color>() {
    @java.lang.Override
    public Color parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Color(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Color> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Color> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.run.Color getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

