// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface ColorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Color)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 r = 1;</code>
   * @return Whether the r field is set.
   */
  boolean hasR();
  /**
   * <code>int32 r = 1;</code>
   * @return The r.
   */
  int getR();

  /**
   * <code>int32 g = 2;</code>
   * @return Whether the g field is set.
   */
  boolean hasG();
  /**
   * <code>int32 g = 2;</code>
   * @return The g.
   */
  int getG();

  /**
   * <code>int32 b = 3;</code>
   * @return Whether the b field is set.
   */
  boolean hasB();
  /**
   * <code>int32 b = 3;</code>
   * @return The b.
   */
  int getB();
}
