// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface CoordinateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Coordinate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
