// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface NetActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.NetAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string netId = 1;</code>
   * @return The netId.
   */
  java.lang.String getNetId();
  /**
   * <code>string netId = 1;</code>
   * @return The bytes for netId.
   */
  com.google.protobuf.ByteString
      getNetIdBytes();

  /**
   * <code>repeated .protobuf.run.Action actions = 2;</code>
   */
  java.util.List<protobuf.run.Action> 
      getActionsList();
  /**
   * <code>repeated .protobuf.run.Action actions = 2;</code>
   */
  protobuf.run.Action getActions(int index);
  /**
   * <code>repeated .protobuf.run.Action actions = 2;</code>
   */
  int getActionsCount();
  /**
   * <code>repeated .protobuf.run.Action actions = 2;</code>
   */
  java.util.List<? extends protobuf.run.ActionOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Action actions = 2;</code>
   */
  protobuf.run.ActionOrBuilder getActionsOrBuilder(
      int index);
}
