// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface NetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Net)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .protobuf.run.Place places = 3;</code>
   */
  java.util.List<protobuf.run.Place> 
      getPlacesList();
  /**
   * <code>repeated .protobuf.run.Place places = 3;</code>
   */
  protobuf.run.Place getPlaces(int index);
  /**
   * <code>repeated .protobuf.run.Place places = 3;</code>
   */
  int getPlacesCount();
  /**
   * <code>repeated .protobuf.run.Place places = 3;</code>
   */
  java.util.List<? extends protobuf.run.PlaceOrBuilder> 
      getPlacesOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Place places = 3;</code>
   */
  protobuf.run.PlaceOrBuilder getPlacesOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.run.Transition transitions = 4;</code>
   */
  java.util.List<protobuf.run.Transition> 
      getTransitionsList();
  /**
   * <code>repeated .protobuf.run.Transition transitions = 4;</code>
   */
  protobuf.run.Transition getTransitions(int index);
  /**
   * <code>repeated .protobuf.run.Transition transitions = 4;</code>
   */
  int getTransitionsCount();
  /**
   * <code>repeated .protobuf.run.Transition transitions = 4;</code>
   */
  java.util.List<? extends protobuf.run.TransitionOrBuilder> 
      getTransitionsOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Transition transitions = 4;</code>
   */
  protobuf.run.TransitionOrBuilder getTransitionsOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.run.Arc arcs = 5;</code>
   */
  java.util.List<protobuf.run.Arc> 
      getArcsList();
  /**
   * <code>repeated .protobuf.run.Arc arcs = 5;</code>
   */
  protobuf.run.Arc getArcs(int index);
  /**
   * <code>repeated .protobuf.run.Arc arcs = 5;</code>
   */
  int getArcsCount();
  /**
   * <code>repeated .protobuf.run.Arc arcs = 5;</code>
   */
  java.util.List<? extends protobuf.run.ArcOrBuilder> 
      getArcsOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Arc arcs = 5;</code>
   */
  protobuf.run.ArcOrBuilder getArcsOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.run.Token tokens = 6;</code>
   */
  java.util.List<protobuf.run.Token> 
      getTokensList();
  /**
   * <code>repeated .protobuf.run.Token tokens = 6;</code>
   */
  protobuf.run.Token getTokens(int index);
  /**
   * <code>repeated .protobuf.run.Token tokens = 6;</code>
   */
  int getTokensCount();
  /**
   * <code>repeated .protobuf.run.Token tokens = 6;</code>
   */
  java.util.List<? extends protobuf.run.TokenOrBuilder> 
      getTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.run.Token tokens = 6;</code>
   */
  protobuf.run.TokenOrBuilder getTokensOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.run.InitialMarking initialMarking = 7;</code>
   */
  java.util.List<protobuf.run.InitialMarking> 
      getInitialMarkingList();
  /**
   * <code>repeated .protobuf.run.InitialMarking initialMarking = 7;</code>
   */
  protobuf.run.InitialMarking getInitialMarking(int index);
  /**
   * <code>repeated .protobuf.run.InitialMarking initialMarking = 7;</code>
   */
  int getInitialMarkingCount();
  /**
   * <code>repeated .protobuf.run.InitialMarking initialMarking = 7;</code>
   */
  java.util.List<? extends protobuf.run.InitialMarkingOrBuilder> 
      getInitialMarkingOrBuilderList();
  /**
   * <code>repeated .protobuf.run.InitialMarking initialMarking = 7;</code>
   */
  protobuf.run.InitialMarkingOrBuilder getInitialMarkingOrBuilder(
      int index);

  /**
   * <code>double positionX = 8;</code>
   * @return Whether the positionX field is set.
   */
  boolean hasPositionX();
  /**
   * <code>double positionX = 8;</code>
   * @return The positionX.
   */
  double getPositionX();

  /**
   * <code>double positionY = 9;</code>
   * @return Whether the positionY field is set.
   */
  boolean hasPositionY();
  /**
   * <code>double positionY = 9;</code>
   * @return The positionY.
   */
  double getPositionY();

  /**
   * <code>repeated .protobuf.run.AgentNet agentNets = 10;</code>
   */
  java.util.List<protobuf.run.AgentNet> 
      getAgentNetsList();
  /**
   * <code>repeated .protobuf.run.AgentNet agentNets = 10;</code>
   */
  protobuf.run.AgentNet getAgentNets(int index);
  /**
   * <code>repeated .protobuf.run.AgentNet agentNets = 10;</code>
   */
  int getAgentNetsCount();
  /**
   * <code>repeated .protobuf.run.AgentNet agentNets = 10;</code>
   */
  java.util.List<? extends protobuf.run.AgentNetOrBuilder> 
      getAgentNetsOrBuilderList();
  /**
   * <code>repeated .protobuf.run.AgentNet agentNets = 10;</code>
   */
  protobuf.run.AgentNetOrBuilder getAgentNetsOrBuilder(
      int index);
}
