// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Run.proto

package protobuf.run;

public interface RunOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.run.Run)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.run.NetAction netActions = 1;</code>
   */
  java.util.List<protobuf.run.NetAction> 
      getNetActionsList();
  /**
   * <code>repeated .protobuf.run.NetAction netActions = 1;</code>
   */
  protobuf.run.NetAction getNetActions(int index);
  /**
   * <code>repeated .protobuf.run.NetAction netActions = 1;</code>
   */
  int getNetActionsCount();
  /**
   * <code>repeated .protobuf.run.NetAction netActions = 1;</code>
   */
  java.util.List<? extends protobuf.run.NetActionOrBuilder> 
      getNetActionsOrBuilderList();
  /**
   * <code>repeated .protobuf.run.NetAction netActions = 1;</code>
   */
  protobuf.run.NetActionOrBuilder getNetActionsOrBuilder(
      int index);

  /**
   * <code>.protobuf.run.Net net = 2;</code>
   * @return Whether the net field is set.
   */
  boolean hasNet();
  /**
   * <code>.protobuf.run.Net net = 2;</code>
   * @return The net.
   */
  protobuf.run.Net getNet();
  /**
   * <code>.protobuf.run.Net net = 2;</code>
   */
  protobuf.run.NetOrBuilder getNetOrBuilder();

  /**
   * <code>int64 endTime = 3;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>int64 endTime = 3;</code>
   * @return The endTime.
   */
  long getEndTime();
}
