// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTrace.proto

package protobuf.usertrace;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.usertrace.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 startTime = 1;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>string eventTypeId = 2;</code>
   * @return The eventTypeId.
   */
  java.lang.String getEventTypeId();
  /**
   * <code>string eventTypeId = 2;</code>
   * @return The bytes for eventTypeId.
   */
  com.google.protobuf.ByteString
      getEventTypeIdBytes();

  /**
   * <code>repeated .protobuf.usertrace.TokenMove removeTokens = 3;</code>
   */
  java.util.List<protobuf.usertrace.TokenMove> 
      getRemoveTokensList();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove removeTokens = 3;</code>
   */
  protobuf.usertrace.TokenMove getRemoveTokens(int index);
  /**
   * <code>repeated .protobuf.usertrace.TokenMove removeTokens = 3;</code>
   */
  int getRemoveTokensCount();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove removeTokens = 3;</code>
   */
  java.util.List<? extends protobuf.usertrace.TokenMoveOrBuilder> 
      getRemoveTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove removeTokens = 3;</code>
   */
  protobuf.usertrace.TokenMoveOrBuilder getRemoveTokensOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usertrace.TokenMove addTokens = 4;</code>
   */
  java.util.List<protobuf.usertrace.TokenMove> 
      getAddTokensList();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove addTokens = 4;</code>
   */
  protobuf.usertrace.TokenMove getAddTokens(int index);
  /**
   * <code>repeated .protobuf.usertrace.TokenMove addTokens = 4;</code>
   */
  int getAddTokensCount();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove addTokens = 4;</code>
   */
  java.util.List<? extends protobuf.usertrace.TokenMoveOrBuilder> 
      getAddTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.usertrace.TokenMove addTokens = 4;</code>
   */
  protobuf.usertrace.TokenMoveOrBuilder getAddTokensOrBuilder(
      int index);

  /**
   * <code>string viaTransitionId = 5;</code>
   * @return The viaTransitionId.
   */
  java.lang.String getViaTransitionId();
  /**
   * <code>string viaTransitionId = 5;</code>
   * @return The bytes for viaTransitionId.
   */
  com.google.protobuf.ByteString
      getViaTransitionIdBytes();
}
