// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTrace.proto

package protobuf.usertrace;

public interface TokenMoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.usertrace.TokenMove)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tokenId = 1;</code>
   * @return The tokenId.
   */
  java.lang.String getTokenId();
  /**
   * <code>string tokenId = 1;</code>
   * @return The bytes for tokenId.
   */
  com.google.protobuf.ByteString
      getTokenIdBytes();

  /**
   * <code>string placeId = 2;</code>
   * @return The placeId.
   */
  java.lang.String getPlaceId();
  /**
   * <code>string placeId = 2;</code>
   * @return The bytes for placeId.
   */
  com.google.protobuf.ByteString
      getPlaceIdBytes();
}
