// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTrace.proto

package protobuf.usertrace;

/**
 * Protobuf type {@code protobuf.usertrace.UserTrace}
 */
public final class UserTrace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.usertrace.UserTrace)
    UserTraceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserTrace.newBuilder() to construct.
  private UserTrace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserTrace() {
    actions_ = java.util.Collections.emptyList();
    eventTypes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserTrace();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserTrace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              actions_ = new java.util.ArrayList<protobuf.usertrace.NetAction>();
              mutable_bitField0_ |= 0x00000001;
            }
            actions_.add(
                input.readMessage(protobuf.usertrace.NetAction.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              eventTypes_ = new java.util.ArrayList<protobuf.usertrace.EventType>();
              mutable_bitField0_ |= 0x00000002;
            }
            eventTypes_.add(
                input.readMessage(protobuf.usertrace.EventType.parser(), extensionRegistry));
            break;
          }
          case 24: {

            endTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        actions_ = java.util.Collections.unmodifiableList(actions_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        eventTypes_ = java.util.Collections.unmodifiableList(eventTypes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.usertrace.UserTraceOuterClass.internal_static_protobuf_usertrace_UserTrace_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.usertrace.UserTraceOuterClass.internal_static_protobuf_usertrace_UserTrace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.usertrace.UserTrace.class, protobuf.usertrace.UserTrace.Builder.class);
  }

  public static final int ACTIONS_FIELD_NUMBER = 1;
  private java.util.List<protobuf.usertrace.NetAction> actions_;
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usertrace.NetAction> getActionsList() {
    return actions_;
  }
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usertrace.NetActionOrBuilder> 
      getActionsOrBuilderList() {
    return actions_;
  }
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  @java.lang.Override
  public int getActionsCount() {
    return actions_.size();
  }
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  @java.lang.Override
  public protobuf.usertrace.NetAction getActions(int index) {
    return actions_.get(index);
  }
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  @java.lang.Override
  public protobuf.usertrace.NetActionOrBuilder getActionsOrBuilder(
      int index) {
    return actions_.get(index);
  }

  public static final int EVENTTYPES_FIELD_NUMBER = 2;
  private java.util.List<protobuf.usertrace.EventType> eventTypes_;
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usertrace.EventType> getEventTypesList() {
    return eventTypes_;
  }
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usertrace.EventTypeOrBuilder> 
      getEventTypesOrBuilderList() {
    return eventTypes_;
  }
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  @java.lang.Override
  public int getEventTypesCount() {
    return eventTypes_.size();
  }
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  @java.lang.Override
  public protobuf.usertrace.EventType getEventTypes(int index) {
    return eventTypes_.get(index);
  }
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  @java.lang.Override
  public protobuf.usertrace.EventTypeOrBuilder getEventTypesOrBuilder(
      int index) {
    return eventTypes_.get(index);
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  private long endTime_;
  /**
   * <code>int64 endTime = 3;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < actions_.size(); i++) {
      output.writeMessage(1, actions_.get(i));
    }
    for (int i = 0; i < eventTypes_.size(); i++) {
      output.writeMessage(2, eventTypes_.get(i));
    }
    if (endTime_ != 0L) {
      output.writeInt64(3, endTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < actions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, actions_.get(i));
    }
    for (int i = 0; i < eventTypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, eventTypes_.get(i));
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, endTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.usertrace.UserTrace)) {
      return super.equals(obj);
    }
    protobuf.usertrace.UserTrace other = (protobuf.usertrace.UserTrace) obj;

    if (!getActionsList()
        .equals(other.getActionsList())) return false;
    if (!getEventTypesList()
        .equals(other.getEventTypesList())) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getActionsCount() > 0) {
      hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getActionsList().hashCode();
    }
    if (getEventTypesCount() > 0) {
      hash = (37 * hash) + EVENTTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getEventTypesList().hashCode();
    }
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.usertrace.UserTrace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usertrace.UserTrace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usertrace.UserTrace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.usertrace.UserTrace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.usertrace.UserTrace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.usertrace.UserTrace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.usertrace.UserTrace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.usertrace.UserTrace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.usertrace.UserTrace)
      protobuf.usertrace.UserTraceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.usertrace.UserTraceOuterClass.internal_static_protobuf_usertrace_UserTrace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.usertrace.UserTraceOuterClass.internal_static_protobuf_usertrace_UserTrace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.usertrace.UserTrace.class, protobuf.usertrace.UserTrace.Builder.class);
    }

    // Construct using protobuf.usertrace.UserTrace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getActionsFieldBuilder();
        getEventTypesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (actionsBuilder_ == null) {
        actions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        actionsBuilder_.clear();
      }
      if (eventTypesBuilder_ == null) {
        eventTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        eventTypesBuilder_.clear();
      }
      endTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.usertrace.UserTraceOuterClass.internal_static_protobuf_usertrace_UserTrace_descriptor;
    }

    @java.lang.Override
    public protobuf.usertrace.UserTrace getDefaultInstanceForType() {
      return protobuf.usertrace.UserTrace.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.usertrace.UserTrace build() {
      protobuf.usertrace.UserTrace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.usertrace.UserTrace buildPartial() {
      protobuf.usertrace.UserTrace result = new protobuf.usertrace.UserTrace(this);
      int from_bitField0_ = bitField0_;
      if (actionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.actions_ = actions_;
      } else {
        result.actions_ = actionsBuilder_.build();
      }
      if (eventTypesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          eventTypes_ = java.util.Collections.unmodifiableList(eventTypes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.eventTypes_ = eventTypes_;
      } else {
        result.eventTypes_ = eventTypesBuilder_.build();
      }
      result.endTime_ = endTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.usertrace.UserTrace) {
        return mergeFrom((protobuf.usertrace.UserTrace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.usertrace.UserTrace other) {
      if (other == protobuf.usertrace.UserTrace.getDefaultInstance()) return this;
      if (actionsBuilder_ == null) {
        if (!other.actions_.isEmpty()) {
          if (actions_.isEmpty()) {
            actions_ = other.actions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActionsIsMutable();
            actions_.addAll(other.actions_);
          }
          onChanged();
        }
      } else {
        if (!other.actions_.isEmpty()) {
          if (actionsBuilder_.isEmpty()) {
            actionsBuilder_.dispose();
            actionsBuilder_ = null;
            actions_ = other.actions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            actionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getActionsFieldBuilder() : null;
          } else {
            actionsBuilder_.addAllMessages(other.actions_);
          }
        }
      }
      if (eventTypesBuilder_ == null) {
        if (!other.eventTypes_.isEmpty()) {
          if (eventTypes_.isEmpty()) {
            eventTypes_ = other.eventTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEventTypesIsMutable();
            eventTypes_.addAll(other.eventTypes_);
          }
          onChanged();
        }
      } else {
        if (!other.eventTypes_.isEmpty()) {
          if (eventTypesBuilder_.isEmpty()) {
            eventTypesBuilder_.dispose();
            eventTypesBuilder_ = null;
            eventTypes_ = other.eventTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            eventTypesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventTypesFieldBuilder() : null;
          } else {
            eventTypesBuilder_.addAllMessages(other.eventTypes_);
          }
        }
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.usertrace.UserTrace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.usertrace.UserTrace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protobuf.usertrace.NetAction> actions_ =
      java.util.Collections.emptyList();
    private void ensureActionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        actions_ = new java.util.ArrayList<protobuf.usertrace.NetAction>(actions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usertrace.NetAction, protobuf.usertrace.NetAction.Builder, protobuf.usertrace.NetActionOrBuilder> actionsBuilder_;

    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public java.util.List<protobuf.usertrace.NetAction> getActionsList() {
      if (actionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(actions_);
      } else {
        return actionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public int getActionsCount() {
      if (actionsBuilder_ == null) {
        return actions_.size();
      } else {
        return actionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public protobuf.usertrace.NetAction getActions(int index) {
      if (actionsBuilder_ == null) {
        return actions_.get(index);
      } else {
        return actionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder setActions(
        int index, protobuf.usertrace.NetAction value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.set(index, value);
        onChanged();
      } else {
        actionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder setActions(
        int index, protobuf.usertrace.NetAction.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.set(index, builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder addActions(protobuf.usertrace.NetAction value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.add(value);
        onChanged();
      } else {
        actionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder addActions(
        int index, protobuf.usertrace.NetAction value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.add(index, value);
        onChanged();
      } else {
        actionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder addActions(
        protobuf.usertrace.NetAction.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.add(builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder addActions(
        int index, protobuf.usertrace.NetAction.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.add(index, builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder addAllActions(
        java.lang.Iterable<? extends protobuf.usertrace.NetAction> values) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, actions_);
        onChanged();
      } else {
        actionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder clearActions() {
      if (actionsBuilder_ == null) {
        actions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        actionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public Builder removeActions(int index) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.remove(index);
        onChanged();
      } else {
        actionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public protobuf.usertrace.NetAction.Builder getActionsBuilder(
        int index) {
      return getActionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public protobuf.usertrace.NetActionOrBuilder getActionsOrBuilder(
        int index) {
      if (actionsBuilder_ == null) {
        return actions_.get(index);  } else {
        return actionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public java.util.List<? extends protobuf.usertrace.NetActionOrBuilder> 
         getActionsOrBuilderList() {
      if (actionsBuilder_ != null) {
        return actionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(actions_);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public protobuf.usertrace.NetAction.Builder addActionsBuilder() {
      return getActionsFieldBuilder().addBuilder(
          protobuf.usertrace.NetAction.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public protobuf.usertrace.NetAction.Builder addActionsBuilder(
        int index) {
      return getActionsFieldBuilder().addBuilder(
          index, protobuf.usertrace.NetAction.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
     */
    public java.util.List<protobuf.usertrace.NetAction.Builder> 
         getActionsBuilderList() {
      return getActionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usertrace.NetAction, protobuf.usertrace.NetAction.Builder, protobuf.usertrace.NetActionOrBuilder> 
        getActionsFieldBuilder() {
      if (actionsBuilder_ == null) {
        actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usertrace.NetAction, protobuf.usertrace.NetAction.Builder, protobuf.usertrace.NetActionOrBuilder>(
                actions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        actions_ = null;
      }
      return actionsBuilder_;
    }

    private java.util.List<protobuf.usertrace.EventType> eventTypes_ =
      java.util.Collections.emptyList();
    private void ensureEventTypesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        eventTypes_ = new java.util.ArrayList<protobuf.usertrace.EventType>(eventTypes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usertrace.EventType, protobuf.usertrace.EventType.Builder, protobuf.usertrace.EventTypeOrBuilder> eventTypesBuilder_;

    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public java.util.List<protobuf.usertrace.EventType> getEventTypesList() {
      if (eventTypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(eventTypes_);
      } else {
        return eventTypesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public int getEventTypesCount() {
      if (eventTypesBuilder_ == null) {
        return eventTypes_.size();
      } else {
        return eventTypesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public protobuf.usertrace.EventType getEventTypes(int index) {
      if (eventTypesBuilder_ == null) {
        return eventTypes_.get(index);
      } else {
        return eventTypesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder setEventTypes(
        int index, protobuf.usertrace.EventType value) {
      if (eventTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventTypesIsMutable();
        eventTypes_.set(index, value);
        onChanged();
      } else {
        eventTypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder setEventTypes(
        int index, protobuf.usertrace.EventType.Builder builderForValue) {
      if (eventTypesBuilder_ == null) {
        ensureEventTypesIsMutable();
        eventTypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventTypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder addEventTypes(protobuf.usertrace.EventType value) {
      if (eventTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventTypesIsMutable();
        eventTypes_.add(value);
        onChanged();
      } else {
        eventTypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder addEventTypes(
        int index, protobuf.usertrace.EventType value) {
      if (eventTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventTypesIsMutable();
        eventTypes_.add(index, value);
        onChanged();
      } else {
        eventTypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder addEventTypes(
        protobuf.usertrace.EventType.Builder builderForValue) {
      if (eventTypesBuilder_ == null) {
        ensureEventTypesIsMutable();
        eventTypes_.add(builderForValue.build());
        onChanged();
      } else {
        eventTypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder addEventTypes(
        int index, protobuf.usertrace.EventType.Builder builderForValue) {
      if (eventTypesBuilder_ == null) {
        ensureEventTypesIsMutable();
        eventTypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventTypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder addAllEventTypes(
        java.lang.Iterable<? extends protobuf.usertrace.EventType> values) {
      if (eventTypesBuilder_ == null) {
        ensureEventTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, eventTypes_);
        onChanged();
      } else {
        eventTypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder clearEventTypes() {
      if (eventTypesBuilder_ == null) {
        eventTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        eventTypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public Builder removeEventTypes(int index) {
      if (eventTypesBuilder_ == null) {
        ensureEventTypesIsMutable();
        eventTypes_.remove(index);
        onChanged();
      } else {
        eventTypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public protobuf.usertrace.EventType.Builder getEventTypesBuilder(
        int index) {
      return getEventTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public protobuf.usertrace.EventTypeOrBuilder getEventTypesOrBuilder(
        int index) {
      if (eventTypesBuilder_ == null) {
        return eventTypes_.get(index);  } else {
        return eventTypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public java.util.List<? extends protobuf.usertrace.EventTypeOrBuilder> 
         getEventTypesOrBuilderList() {
      if (eventTypesBuilder_ != null) {
        return eventTypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(eventTypes_);
      }
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public protobuf.usertrace.EventType.Builder addEventTypesBuilder() {
      return getEventTypesFieldBuilder().addBuilder(
          protobuf.usertrace.EventType.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public protobuf.usertrace.EventType.Builder addEventTypesBuilder(
        int index) {
      return getEventTypesFieldBuilder().addBuilder(
          index, protobuf.usertrace.EventType.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
     */
    public java.util.List<protobuf.usertrace.EventType.Builder> 
         getEventTypesBuilderList() {
      return getEventTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usertrace.EventType, protobuf.usertrace.EventType.Builder, protobuf.usertrace.EventTypeOrBuilder> 
        getEventTypesFieldBuilder() {
      if (eventTypesBuilder_ == null) {
        eventTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usertrace.EventType, protobuf.usertrace.EventType.Builder, protobuf.usertrace.EventTypeOrBuilder>(
                eventTypes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        eventTypes_ = null;
      }
      return eventTypesBuilder_;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 3;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 3;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.usertrace.UserTrace)
  }

  // @@protoc_insertion_point(class_scope:protobuf.usertrace.UserTrace)
  private static final protobuf.usertrace.UserTrace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.usertrace.UserTrace();
  }

  public static protobuf.usertrace.UserTrace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserTrace>
      PARSER = new com.google.protobuf.AbstractParser<UserTrace>() {
    @java.lang.Override
    public UserTrace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserTrace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserTrace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserTrace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.usertrace.UserTrace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

