// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTrace.proto

package protobuf.usertrace;

public interface UserTraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.usertrace.UserTrace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  java.util.List<protobuf.usertrace.NetAction> 
      getActionsList();
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  protobuf.usertrace.NetAction getActions(int index);
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  int getActionsCount();
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  java.util.List<? extends protobuf.usertrace.NetActionOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <code>repeated .protobuf.usertrace.NetAction actions = 1;</code>
   */
  protobuf.usertrace.NetActionOrBuilder getActionsOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  java.util.List<protobuf.usertrace.EventType> 
      getEventTypesList();
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  protobuf.usertrace.EventType getEventTypes(int index);
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  int getEventTypesCount();
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  java.util.List<? extends protobuf.usertrace.EventTypeOrBuilder> 
      getEventTypesOrBuilderList();
  /**
   * <code>repeated .protobuf.usertrace.EventType eventTypes = 2;</code>
   */
  protobuf.usertrace.EventTypeOrBuilder getEventTypesOrBuilder(
      int index);

  /**
   * <code>int64 endTime = 3;</code>
   * @return The endTime.
   */
  long getEndTime();
}
