// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserNet.proto

package protobuf.usernet;

/**
 * Protobuf type {@code protobuf.usernet.AgentNet}
 */
public final class AgentNet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.usernet.AgentNet)
    AgentNetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentNet.newBuilder() to construct.
  private AgentNet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentNet() {
    id_ = "";
    name_ = "";
    startPlaceId_ = "";
    places_ = java.util.Collections.emptyList();
    transitions_ = java.util.Collections.emptyList();
    arcs_ = java.util.Collections.emptyList();
    tokens_ = java.util.Collections.emptyList();
    initialMarking_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentNet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AgentNet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            startPlaceId_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              places_ = new java.util.ArrayList<protobuf.usernet.Place>();
              mutable_bitField0_ |= 0x00000002;
            }
            places_.add(
                input.readMessage(protobuf.usernet.Place.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              transitions_ = new java.util.ArrayList<protobuf.usernet.Transition>();
              mutable_bitField0_ |= 0x00000004;
            }
            transitions_.add(
                input.readMessage(protobuf.usernet.Transition.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              arcs_ = new java.util.ArrayList<protobuf.usernet.Arc>();
              mutable_bitField0_ |= 0x00000008;
            }
            arcs_.add(
                input.readMessage(protobuf.usernet.Arc.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              tokens_ = new java.util.ArrayList<protobuf.usernet.Token>();
              mutable_bitField0_ |= 0x00000010;
            }
            tokens_.add(
                input.readMessage(protobuf.usernet.Token.parser(), extensionRegistry));
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              initialMarking_ = new java.util.ArrayList<protobuf.usernet.InitialMarking>();
              mutable_bitField0_ |= 0x00000020;
            }
            initialMarking_.add(
                input.readMessage(protobuf.usernet.InitialMarking.parser(), extensionRegistry));
            break;
          }
          case 80: {
            bitField0_ |= 0x00000002;
            threshold_ = input.readInt64();
            break;
          }
          case 88: {
            bitField0_ |= 0x00000004;
            intervalDuration_ = input.readInt64();
            break;
          }
          case 96: {
            bitField0_ |= 0x00000008;
            distanceBetweenIntervals_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        places_ = java.util.Collections.unmodifiableList(places_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        transitions_ = java.util.Collections.unmodifiableList(transitions_);
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        arcs_ = java.util.Collections.unmodifiableList(arcs_);
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        tokens_ = java.util.Collections.unmodifiableList(tokens_);
      }
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        initialMarking_ = java.util.Collections.unmodifiableList(initialMarking_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.usernet.UserNetOuterClass.internal_static_protobuf_usernet_AgentNet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.usernet.UserNetOuterClass.internal_static_protobuf_usernet_AgentNet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.usernet.AgentNet.class, protobuf.usernet.AgentNet.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTPLACEID_FIELD_NUMBER = 4;
  private volatile java.lang.Object startPlaceId_;
  /**
   * <code>string startPlaceId = 4;</code>
   * @return The startPlaceId.
   */
  @java.lang.Override
  public java.lang.String getStartPlaceId() {
    java.lang.Object ref = startPlaceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startPlaceId_ = s;
      return s;
    }
  }
  /**
   * <code>string startPlaceId = 4;</code>
   * @return The bytes for startPlaceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartPlaceIdBytes() {
    java.lang.Object ref = startPlaceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startPlaceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLACES_FIELD_NUMBER = 5;
  private java.util.List<protobuf.usernet.Place> places_;
  /**
   * <code>repeated .protobuf.usernet.Place places = 5;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usernet.Place> getPlacesList() {
    return places_;
  }
  /**
   * <code>repeated .protobuf.usernet.Place places = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usernet.PlaceOrBuilder> 
      getPlacesOrBuilderList() {
    return places_;
  }
  /**
   * <code>repeated .protobuf.usernet.Place places = 5;</code>
   */
  @java.lang.Override
  public int getPlacesCount() {
    return places_.size();
  }
  /**
   * <code>repeated .protobuf.usernet.Place places = 5;</code>
   */
  @java.lang.Override
  public protobuf.usernet.Place getPlaces(int index) {
    return places_.get(index);
  }
  /**
   * <code>repeated .protobuf.usernet.Place places = 5;</code>
   */
  @java.lang.Override
  public protobuf.usernet.PlaceOrBuilder getPlacesOrBuilder(
      int index) {
    return places_.get(index);
  }

  public static final int TRANSITIONS_FIELD_NUMBER = 6;
  private java.util.List<protobuf.usernet.Transition> transitions_;
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usernet.Transition> getTransitionsList() {
    return transitions_;
  }
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usernet.TransitionOrBuilder> 
      getTransitionsOrBuilderList() {
    return transitions_;
  }
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
   */
  @java.lang.Override
  public int getTransitionsCount() {
    return transitions_.size();
  }
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
   */
  @java.lang.Override
  public protobuf.usernet.Transition getTransitions(int index) {
    return transitions_.get(index);
  }
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
   */
  @java.lang.Override
  public protobuf.usernet.TransitionOrBuilder getTransitionsOrBuilder(
      int index) {
    return transitions_.get(index);
  }

  public static final int ARCS_FIELD_NUMBER = 7;
  private java.util.List<protobuf.usernet.Arc> arcs_;
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usernet.Arc> getArcsList() {
    return arcs_;
  }
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usernet.ArcOrBuilder> 
      getArcsOrBuilderList() {
    return arcs_;
  }
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
   */
  @java.lang.Override
  public int getArcsCount() {
    return arcs_.size();
  }
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
   */
  @java.lang.Override
  public protobuf.usernet.Arc getArcs(int index) {
    return arcs_.get(index);
  }
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
   */
  @java.lang.Override
  public protobuf.usernet.ArcOrBuilder getArcsOrBuilder(
      int index) {
    return arcs_.get(index);
  }

  public static final int TOKENS_FIELD_NUMBER = 8;
  private java.util.List<protobuf.usernet.Token> tokens_;
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usernet.Token> getTokensList() {
    return tokens_;
  }
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usernet.TokenOrBuilder> 
      getTokensOrBuilderList() {
    return tokens_;
  }
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
   */
  @java.lang.Override
  public int getTokensCount() {
    return tokens_.size();
  }
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
   */
  @java.lang.Override
  public protobuf.usernet.Token getTokens(int index) {
    return tokens_.get(index);
  }
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
   */
  @java.lang.Override
  public protobuf.usernet.TokenOrBuilder getTokensOrBuilder(
      int index) {
    return tokens_.get(index);
  }

  public static final int INITIALMARKING_FIELD_NUMBER = 9;
  private java.util.List<protobuf.usernet.InitialMarking> initialMarking_;
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.usernet.InitialMarking> getInitialMarkingList() {
    return initialMarking_;
  }
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.usernet.InitialMarkingOrBuilder> 
      getInitialMarkingOrBuilderList() {
    return initialMarking_;
  }
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
   */
  @java.lang.Override
  public int getInitialMarkingCount() {
    return initialMarking_.size();
  }
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
   */
  @java.lang.Override
  public protobuf.usernet.InitialMarking getInitialMarking(int index) {
    return initialMarking_.get(index);
  }
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
   */
  @java.lang.Override
  public protobuf.usernet.InitialMarkingOrBuilder getInitialMarkingOrBuilder(
      int index) {
    return initialMarking_.get(index);
  }

  public static final int THRESHOLD_FIELD_NUMBER = 10;
  private long threshold_;
  /**
   * <code>int64 threshold = 10;</code>
   * @return Whether the threshold field is set.
   */
  @java.lang.Override
  public boolean hasThreshold() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>int64 threshold = 10;</code>
   * @return The threshold.
   */
  @java.lang.Override
  public long getThreshold() {
    return threshold_;
  }

  public static final int INTERVALDURATION_FIELD_NUMBER = 11;
  private long intervalDuration_;
  /**
   * <code>int64 intervalDuration = 11;</code>
   * @return Whether the intervalDuration field is set.
   */
  @java.lang.Override
  public boolean hasIntervalDuration() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>int64 intervalDuration = 11;</code>
   * @return The intervalDuration.
   */
  @java.lang.Override
  public long getIntervalDuration() {
    return intervalDuration_;
  }

  public static final int DISTANCEBETWEENINTERVALS_FIELD_NUMBER = 12;
  private long distanceBetweenIntervals_;
  /**
   * <code>int64 distanceBetweenIntervals = 12;</code>
   * @return Whether the distanceBetweenIntervals field is set.
   */
  @java.lang.Override
  public boolean hasDistanceBetweenIntervals() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>int64 distanceBetweenIntervals = 12;</code>
   * @return The distanceBetweenIntervals.
   */
  @java.lang.Override
  public long getDistanceBetweenIntervals() {
    return distanceBetweenIntervals_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getStartPlaceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, startPlaceId_);
    }
    for (int i = 0; i < places_.size(); i++) {
      output.writeMessage(5, places_.get(i));
    }
    for (int i = 0; i < transitions_.size(); i++) {
      output.writeMessage(6, transitions_.get(i));
    }
    for (int i = 0; i < arcs_.size(); i++) {
      output.writeMessage(7, arcs_.get(i));
    }
    for (int i = 0; i < tokens_.size(); i++) {
      output.writeMessage(8, tokens_.get(i));
    }
    for (int i = 0; i < initialMarking_.size(); i++) {
      output.writeMessage(9, initialMarking_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(10, threshold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(11, intervalDuration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(12, distanceBetweenIntervals_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getStartPlaceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, startPlaceId_);
    }
    for (int i = 0; i < places_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, places_.get(i));
    }
    for (int i = 0; i < transitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, transitions_.get(i));
    }
    for (int i = 0; i < arcs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, arcs_.get(i));
    }
    for (int i = 0; i < tokens_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, tokens_.get(i));
    }
    for (int i = 0; i < initialMarking_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, initialMarking_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, threshold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, intervalDuration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, distanceBetweenIntervals_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.usernet.AgentNet)) {
      return super.equals(obj);
    }
    protobuf.usernet.AgentNet other = (protobuf.usernet.AgentNet) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!getStartPlaceId()
        .equals(other.getStartPlaceId())) return false;
    if (!getPlacesList()
        .equals(other.getPlacesList())) return false;
    if (!getTransitionsList()
        .equals(other.getTransitionsList())) return false;
    if (!getArcsList()
        .equals(other.getArcsList())) return false;
    if (!getTokensList()
        .equals(other.getTokensList())) return false;
    if (!getInitialMarkingList()
        .equals(other.getInitialMarkingList())) return false;
    if (hasThreshold() != other.hasThreshold()) return false;
    if (hasThreshold()) {
      if (getThreshold()
          != other.getThreshold()) return false;
    }
    if (hasIntervalDuration() != other.hasIntervalDuration()) return false;
    if (hasIntervalDuration()) {
      if (getIntervalDuration()
          != other.getIntervalDuration()) return false;
    }
    if (hasDistanceBetweenIntervals() != other.hasDistanceBetweenIntervals()) return false;
    if (hasDistanceBetweenIntervals()) {
      if (getDistanceBetweenIntervals()
          != other.getDistanceBetweenIntervals()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    hash = (37 * hash) + STARTPLACEID_FIELD_NUMBER;
    hash = (53 * hash) + getStartPlaceId().hashCode();
    if (getPlacesCount() > 0) {
      hash = (37 * hash) + PLACES_FIELD_NUMBER;
      hash = (53 * hash) + getPlacesList().hashCode();
    }
    if (getTransitionsCount() > 0) {
      hash = (37 * hash) + TRANSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransitionsList().hashCode();
    }
    if (getArcsCount() > 0) {
      hash = (37 * hash) + ARCS_FIELD_NUMBER;
      hash = (53 * hash) + getArcsList().hashCode();
    }
    if (getTokensCount() > 0) {
      hash = (37 * hash) + TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getTokensList().hashCode();
    }
    if (getInitialMarkingCount() > 0) {
      hash = (37 * hash) + INITIALMARKING_FIELD_NUMBER;
      hash = (53 * hash) + getInitialMarkingList().hashCode();
    }
    if (hasThreshold()) {
      hash = (37 * hash) + THRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getThreshold());
    }
    if (hasIntervalDuration()) {
      hash = (37 * hash) + INTERVALDURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIntervalDuration());
    }
    if (hasDistanceBetweenIntervals()) {
      hash = (37 * hash) + DISTANCEBETWEENINTERVALS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDistanceBetweenIntervals());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.usernet.AgentNet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usernet.AgentNet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.usernet.AgentNet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.usernet.AgentNet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.usernet.AgentNet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.usernet.AgentNet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.usernet.AgentNet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.usernet.AgentNet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.usernet.AgentNet)
      protobuf.usernet.AgentNetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.usernet.UserNetOuterClass.internal_static_protobuf_usernet_AgentNet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.usernet.UserNetOuterClass.internal_static_protobuf_usernet_AgentNet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.usernet.AgentNet.class, protobuf.usernet.AgentNet.Builder.class);
    }

    // Construct using protobuf.usernet.AgentNet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlacesFieldBuilder();
        getTransitionsFieldBuilder();
        getArcsFieldBuilder();
        getTokensFieldBuilder();
        getInitialMarkingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      startPlaceId_ = "";

      if (placesBuilder_ == null) {
        places_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        placesBuilder_.clear();
      }
      if (transitionsBuilder_ == null) {
        transitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        transitionsBuilder_.clear();
      }
      if (arcsBuilder_ == null) {
        arcs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        arcsBuilder_.clear();
      }
      if (tokensBuilder_ == null) {
        tokens_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        tokensBuilder_.clear();
      }
      if (initialMarkingBuilder_ == null) {
        initialMarking_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        initialMarkingBuilder_.clear();
      }
      threshold_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      intervalDuration_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      distanceBetweenIntervals_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.usernet.UserNetOuterClass.internal_static_protobuf_usernet_AgentNet_descriptor;
    }

    @java.lang.Override
    public protobuf.usernet.AgentNet getDefaultInstanceForType() {
      return protobuf.usernet.AgentNet.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.usernet.AgentNet build() {
      protobuf.usernet.AgentNet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.usernet.AgentNet buildPartial() {
      protobuf.usernet.AgentNet result = new protobuf.usernet.AgentNet(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      result.startPlaceId_ = startPlaceId_;
      if (placesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          places_ = java.util.Collections.unmodifiableList(places_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.places_ = places_;
      } else {
        result.places_ = placesBuilder_.build();
      }
      if (transitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          transitions_ = java.util.Collections.unmodifiableList(transitions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.transitions_ = transitions_;
      } else {
        result.transitions_ = transitionsBuilder_.build();
      }
      if (arcsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          arcs_ = java.util.Collections.unmodifiableList(arcs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.arcs_ = arcs_;
      } else {
        result.arcs_ = arcsBuilder_.build();
      }
      if (tokensBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          tokens_ = java.util.Collections.unmodifiableList(tokens_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.tokens_ = tokens_;
      } else {
        result.tokens_ = tokensBuilder_.build();
      }
      if (initialMarkingBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          initialMarking_ = java.util.Collections.unmodifiableList(initialMarking_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.initialMarking_ = initialMarking_;
      } else {
        result.initialMarking_ = initialMarkingBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.threshold_ = threshold_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.intervalDuration_ = intervalDuration_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.distanceBetweenIntervals_ = distanceBetweenIntervals_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.usernet.AgentNet) {
        return mergeFrom((protobuf.usernet.AgentNet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.usernet.AgentNet other) {
      if (other == protobuf.usernet.AgentNet.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (!other.getStartPlaceId().isEmpty()) {
        startPlaceId_ = other.startPlaceId_;
        onChanged();
      }
      if (placesBuilder_ == null) {
        if (!other.places_.isEmpty()) {
          if (places_.isEmpty()) {
            places_ = other.places_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePlacesIsMutable();
            places_.addAll(other.places_);
          }
          onChanged();
        }
      } else {
        if (!other.places_.isEmpty()) {
          if (placesBuilder_.isEmpty()) {
            placesBuilder_.dispose();
            placesBuilder_ = null;
            places_ = other.places_;
            bitField0_ = (bitField0_ & ~0x00000002);
            placesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlacesFieldBuilder() : null;
          } else {
            placesBuilder_.addAllMessages(other.places_);
          }
        }
      }
      if (transitionsBuilder_ == null) {
        if (!other.transitions_.isEmpty()) {
          if (transitions_.isEmpty()) {
            transitions_ = other.transitions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTransitionsIsMutable();
            transitions_.addAll(other.transitions_);
          }
          onChanged();
        }
      } else {
        if (!other.transitions_.isEmpty()) {
          if (transitionsBuilder_.isEmpty()) {
            transitionsBuilder_.dispose();
            transitionsBuilder_ = null;
            transitions_ = other.transitions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            transitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransitionsFieldBuilder() : null;
          } else {
            transitionsBuilder_.addAllMessages(other.transitions_);
          }
        }
      }
      if (arcsBuilder_ == null) {
        if (!other.arcs_.isEmpty()) {
          if (arcs_.isEmpty()) {
            arcs_ = other.arcs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureArcsIsMutable();
            arcs_.addAll(other.arcs_);
          }
          onChanged();
        }
      } else {
        if (!other.arcs_.isEmpty()) {
          if (arcsBuilder_.isEmpty()) {
            arcsBuilder_.dispose();
            arcsBuilder_ = null;
            arcs_ = other.arcs_;
            bitField0_ = (bitField0_ & ~0x00000008);
            arcsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArcsFieldBuilder() : null;
          } else {
            arcsBuilder_.addAllMessages(other.arcs_);
          }
        }
      }
      if (tokensBuilder_ == null) {
        if (!other.tokens_.isEmpty()) {
          if (tokens_.isEmpty()) {
            tokens_ = other.tokens_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTokensIsMutable();
            tokens_.addAll(other.tokens_);
          }
          onChanged();
        }
      } else {
        if (!other.tokens_.isEmpty()) {
          if (tokensBuilder_.isEmpty()) {
            tokensBuilder_.dispose();
            tokensBuilder_ = null;
            tokens_ = other.tokens_;
            bitField0_ = (bitField0_ & ~0x00000010);
            tokensBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTokensFieldBuilder() : null;
          } else {
            tokensBuilder_.addAllMessages(other.tokens_);
          }
        }
      }
      if (initialMarkingBuilder_ == null) {
        if (!other.initialMarking_.isEmpty()) {
          if (initialMarking_.isEmpty()) {
            initialMarking_ = other.initialMarking_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureInitialMarkingIsMutable();
            initialMarking_.addAll(other.initialMarking_);
          }
          onChanged();
        }
      } else {
        if (!other.initialMarking_.isEmpty()) {
          if (initialMarkingBuilder_.isEmpty()) {
            initialMarkingBuilder_.dispose();
            initialMarkingBuilder_ = null;
            initialMarking_ = other.initialMarking_;
            bitField0_ = (bitField0_ & ~0x00000020);
            initialMarkingBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInitialMarkingFieldBuilder() : null;
          } else {
            initialMarkingBuilder_.addAllMessages(other.initialMarking_);
          }
        }
      }
      if (other.hasThreshold()) {
        setThreshold(other.getThreshold());
      }
      if (other.hasIntervalDuration()) {
        setIntervalDuration(other.getIntervalDuration());
      }
      if (other.hasDistanceBetweenIntervals()) {
        setDistanceBetweenIntervals(other.getDistanceBetweenIntervals());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.usernet.AgentNet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.usernet.AgentNet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object startPlaceId_ = "";
    /**
     * <code>string startPlaceId = 4;</code>
     * @return The startPlaceId.
     */
    public java.lang.String getStartPlaceId() {
      java.lang.Object ref = startPlaceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startPlaceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string startPlaceId = 4;</code>
     * @return The bytes for startPlaceId.
     */
    public com.google.protobuf.ByteString
        getStartPlaceIdBytes() {
      java.lang.Object ref = startPlaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startPlaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string startPlaceId = 4;</code>
     * @param value The startPlaceId to set.
     * @return This builder for chaining.
     */
    public Builder setStartPlaceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startPlaceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string startPlaceId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartPlaceId() {
      
      startPlaceId_ = getDefaultInstance().getStartPlaceId();
      onChanged();
      return this;
    }
    /**
     * <code>string startPlaceId = 4;</code>
     * @param value The bytes for startPlaceId to set.
     * @return This builder for chaining.
     */
    public Builder setStartPlaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startPlaceId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<protobuf.usernet.Place> places_ =
      java.util.Collections.emptyList();
    private void ensurePlacesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        places_ = new java.util.ArrayList<protobuf.usernet.Place>(places_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Place, protobuf.usernet.Place.Builder, protobuf.usernet.PlaceOrBuilder> placesBuilder_;

    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public java.util.List<protobuf.usernet.Place> getPlacesList() {
      if (placesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(places_);
      } else {
        return placesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public int getPlacesCount() {
      if (placesBuilder_ == null) {
        return places_.size();
      } else {
        return placesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public protobuf.usernet.Place getPlaces(int index) {
      if (placesBuilder_ == null) {
        return places_.get(index);
      } else {
        return placesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder setPlaces(
        int index, protobuf.usernet.Place value) {
      if (placesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlacesIsMutable();
        places_.set(index, value);
        onChanged();
      } else {
        placesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder setPlaces(
        int index, protobuf.usernet.Place.Builder builderForValue) {
      if (placesBuilder_ == null) {
        ensurePlacesIsMutable();
        places_.set(index, builderForValue.build());
        onChanged();
      } else {
        placesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder addPlaces(protobuf.usernet.Place value) {
      if (placesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlacesIsMutable();
        places_.add(value);
        onChanged();
      } else {
        placesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder addPlaces(
        int index, protobuf.usernet.Place value) {
      if (placesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlacesIsMutable();
        places_.add(index, value);
        onChanged();
      } else {
        placesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder addPlaces(
        protobuf.usernet.Place.Builder builderForValue) {
      if (placesBuilder_ == null) {
        ensurePlacesIsMutable();
        places_.add(builderForValue.build());
        onChanged();
      } else {
        placesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder addPlaces(
        int index, protobuf.usernet.Place.Builder builderForValue) {
      if (placesBuilder_ == null) {
        ensurePlacesIsMutable();
        places_.add(index, builderForValue.build());
        onChanged();
      } else {
        placesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder addAllPlaces(
        java.lang.Iterable<? extends protobuf.usernet.Place> values) {
      if (placesBuilder_ == null) {
        ensurePlacesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, places_);
        onChanged();
      } else {
        placesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder clearPlaces() {
      if (placesBuilder_ == null) {
        places_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        placesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public Builder removePlaces(int index) {
      if (placesBuilder_ == null) {
        ensurePlacesIsMutable();
        places_.remove(index);
        onChanged();
      } else {
        placesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public protobuf.usernet.Place.Builder getPlacesBuilder(
        int index) {
      return getPlacesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public protobuf.usernet.PlaceOrBuilder getPlacesOrBuilder(
        int index) {
      if (placesBuilder_ == null) {
        return places_.get(index);  } else {
        return placesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public java.util.List<? extends protobuf.usernet.PlaceOrBuilder> 
         getPlacesOrBuilderList() {
      if (placesBuilder_ != null) {
        return placesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(places_);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public protobuf.usernet.Place.Builder addPlacesBuilder() {
      return getPlacesFieldBuilder().addBuilder(
          protobuf.usernet.Place.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public protobuf.usernet.Place.Builder addPlacesBuilder(
        int index) {
      return getPlacesFieldBuilder().addBuilder(
          index, protobuf.usernet.Place.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Place places = 5;</code>
     */
    public java.util.List<protobuf.usernet.Place.Builder> 
         getPlacesBuilderList() {
      return getPlacesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Place, protobuf.usernet.Place.Builder, protobuf.usernet.PlaceOrBuilder> 
        getPlacesFieldBuilder() {
      if (placesBuilder_ == null) {
        placesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usernet.Place, protobuf.usernet.Place.Builder, protobuf.usernet.PlaceOrBuilder>(
                places_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        places_ = null;
      }
      return placesBuilder_;
    }

    private java.util.List<protobuf.usernet.Transition> transitions_ =
      java.util.Collections.emptyList();
    private void ensureTransitionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        transitions_ = new java.util.ArrayList<protobuf.usernet.Transition>(transitions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Transition, protobuf.usernet.Transition.Builder, protobuf.usernet.TransitionOrBuilder> transitionsBuilder_;

    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public java.util.List<protobuf.usernet.Transition> getTransitionsList() {
      if (transitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transitions_);
      } else {
        return transitionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public int getTransitionsCount() {
      if (transitionsBuilder_ == null) {
        return transitions_.size();
      } else {
        return transitionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public protobuf.usernet.Transition getTransitions(int index) {
      if (transitionsBuilder_ == null) {
        return transitions_.get(index);
      } else {
        return transitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder setTransitions(
        int index, protobuf.usernet.Transition value) {
      if (transitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransitionsIsMutable();
        transitions_.set(index, value);
        onChanged();
      } else {
        transitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder setTransitions(
        int index, protobuf.usernet.Transition.Builder builderForValue) {
      if (transitionsBuilder_ == null) {
        ensureTransitionsIsMutable();
        transitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder addTransitions(protobuf.usernet.Transition value) {
      if (transitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransitionsIsMutable();
        transitions_.add(value);
        onChanged();
      } else {
        transitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder addTransitions(
        int index, protobuf.usernet.Transition value) {
      if (transitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransitionsIsMutable();
        transitions_.add(index, value);
        onChanged();
      } else {
        transitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder addTransitions(
        protobuf.usernet.Transition.Builder builderForValue) {
      if (transitionsBuilder_ == null) {
        ensureTransitionsIsMutable();
        transitions_.add(builderForValue.build());
        onChanged();
      } else {
        transitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder addTransitions(
        int index, protobuf.usernet.Transition.Builder builderForValue) {
      if (transitionsBuilder_ == null) {
        ensureTransitionsIsMutable();
        transitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder addAllTransitions(
        java.lang.Iterable<? extends protobuf.usernet.Transition> values) {
      if (transitionsBuilder_ == null) {
        ensureTransitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transitions_);
        onChanged();
      } else {
        transitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder clearTransitions() {
      if (transitionsBuilder_ == null) {
        transitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        transitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public Builder removeTransitions(int index) {
      if (transitionsBuilder_ == null) {
        ensureTransitionsIsMutable();
        transitions_.remove(index);
        onChanged();
      } else {
        transitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public protobuf.usernet.Transition.Builder getTransitionsBuilder(
        int index) {
      return getTransitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public protobuf.usernet.TransitionOrBuilder getTransitionsOrBuilder(
        int index) {
      if (transitionsBuilder_ == null) {
        return transitions_.get(index);  } else {
        return transitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public java.util.List<? extends protobuf.usernet.TransitionOrBuilder> 
         getTransitionsOrBuilderList() {
      if (transitionsBuilder_ != null) {
        return transitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transitions_);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public protobuf.usernet.Transition.Builder addTransitionsBuilder() {
      return getTransitionsFieldBuilder().addBuilder(
          protobuf.usernet.Transition.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public protobuf.usernet.Transition.Builder addTransitionsBuilder(
        int index) {
      return getTransitionsFieldBuilder().addBuilder(
          index, protobuf.usernet.Transition.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Transition transitions = 6;</code>
     */
    public java.util.List<protobuf.usernet.Transition.Builder> 
         getTransitionsBuilderList() {
      return getTransitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Transition, protobuf.usernet.Transition.Builder, protobuf.usernet.TransitionOrBuilder> 
        getTransitionsFieldBuilder() {
      if (transitionsBuilder_ == null) {
        transitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usernet.Transition, protobuf.usernet.Transition.Builder, protobuf.usernet.TransitionOrBuilder>(
                transitions_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        transitions_ = null;
      }
      return transitionsBuilder_;
    }

    private java.util.List<protobuf.usernet.Arc> arcs_ =
      java.util.Collections.emptyList();
    private void ensureArcsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        arcs_ = new java.util.ArrayList<protobuf.usernet.Arc>(arcs_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Arc, protobuf.usernet.Arc.Builder, protobuf.usernet.ArcOrBuilder> arcsBuilder_;

    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public java.util.List<protobuf.usernet.Arc> getArcsList() {
      if (arcsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(arcs_);
      } else {
        return arcsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public int getArcsCount() {
      if (arcsBuilder_ == null) {
        return arcs_.size();
      } else {
        return arcsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public protobuf.usernet.Arc getArcs(int index) {
      if (arcsBuilder_ == null) {
        return arcs_.get(index);
      } else {
        return arcsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder setArcs(
        int index, protobuf.usernet.Arc value) {
      if (arcsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArcsIsMutable();
        arcs_.set(index, value);
        onChanged();
      } else {
        arcsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder setArcs(
        int index, protobuf.usernet.Arc.Builder builderForValue) {
      if (arcsBuilder_ == null) {
        ensureArcsIsMutable();
        arcs_.set(index, builderForValue.build());
        onChanged();
      } else {
        arcsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder addArcs(protobuf.usernet.Arc value) {
      if (arcsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArcsIsMutable();
        arcs_.add(value);
        onChanged();
      } else {
        arcsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder addArcs(
        int index, protobuf.usernet.Arc value) {
      if (arcsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArcsIsMutable();
        arcs_.add(index, value);
        onChanged();
      } else {
        arcsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder addArcs(
        protobuf.usernet.Arc.Builder builderForValue) {
      if (arcsBuilder_ == null) {
        ensureArcsIsMutable();
        arcs_.add(builderForValue.build());
        onChanged();
      } else {
        arcsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder addArcs(
        int index, protobuf.usernet.Arc.Builder builderForValue) {
      if (arcsBuilder_ == null) {
        ensureArcsIsMutable();
        arcs_.add(index, builderForValue.build());
        onChanged();
      } else {
        arcsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder addAllArcs(
        java.lang.Iterable<? extends protobuf.usernet.Arc> values) {
      if (arcsBuilder_ == null) {
        ensureArcsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arcs_);
        onChanged();
      } else {
        arcsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder clearArcs() {
      if (arcsBuilder_ == null) {
        arcs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        arcsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public Builder removeArcs(int index) {
      if (arcsBuilder_ == null) {
        ensureArcsIsMutable();
        arcs_.remove(index);
        onChanged();
      } else {
        arcsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public protobuf.usernet.Arc.Builder getArcsBuilder(
        int index) {
      return getArcsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public protobuf.usernet.ArcOrBuilder getArcsOrBuilder(
        int index) {
      if (arcsBuilder_ == null) {
        return arcs_.get(index);  } else {
        return arcsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public java.util.List<? extends protobuf.usernet.ArcOrBuilder> 
         getArcsOrBuilderList() {
      if (arcsBuilder_ != null) {
        return arcsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(arcs_);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public protobuf.usernet.Arc.Builder addArcsBuilder() {
      return getArcsFieldBuilder().addBuilder(
          protobuf.usernet.Arc.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public protobuf.usernet.Arc.Builder addArcsBuilder(
        int index) {
      return getArcsFieldBuilder().addBuilder(
          index, protobuf.usernet.Arc.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Arc arcs = 7;</code>
     */
    public java.util.List<protobuf.usernet.Arc.Builder> 
         getArcsBuilderList() {
      return getArcsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Arc, protobuf.usernet.Arc.Builder, protobuf.usernet.ArcOrBuilder> 
        getArcsFieldBuilder() {
      if (arcsBuilder_ == null) {
        arcsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usernet.Arc, protobuf.usernet.Arc.Builder, protobuf.usernet.ArcOrBuilder>(
                arcs_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        arcs_ = null;
      }
      return arcsBuilder_;
    }

    private java.util.List<protobuf.usernet.Token> tokens_ =
      java.util.Collections.emptyList();
    private void ensureTokensIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        tokens_ = new java.util.ArrayList<protobuf.usernet.Token>(tokens_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Token, protobuf.usernet.Token.Builder, protobuf.usernet.TokenOrBuilder> tokensBuilder_;

    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public java.util.List<protobuf.usernet.Token> getTokensList() {
      if (tokensBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tokens_);
      } else {
        return tokensBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public int getTokensCount() {
      if (tokensBuilder_ == null) {
        return tokens_.size();
      } else {
        return tokensBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public protobuf.usernet.Token getTokens(int index) {
      if (tokensBuilder_ == null) {
        return tokens_.get(index);
      } else {
        return tokensBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder setTokens(
        int index, protobuf.usernet.Token value) {
      if (tokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTokensIsMutable();
        tokens_.set(index, value);
        onChanged();
      } else {
        tokensBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder setTokens(
        int index, protobuf.usernet.Token.Builder builderForValue) {
      if (tokensBuilder_ == null) {
        ensureTokensIsMutable();
        tokens_.set(index, builderForValue.build());
        onChanged();
      } else {
        tokensBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder addTokens(protobuf.usernet.Token value) {
      if (tokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTokensIsMutable();
        tokens_.add(value);
        onChanged();
      } else {
        tokensBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder addTokens(
        int index, protobuf.usernet.Token value) {
      if (tokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTokensIsMutable();
        tokens_.add(index, value);
        onChanged();
      } else {
        tokensBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder addTokens(
        protobuf.usernet.Token.Builder builderForValue) {
      if (tokensBuilder_ == null) {
        ensureTokensIsMutable();
        tokens_.add(builderForValue.build());
        onChanged();
      } else {
        tokensBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder addTokens(
        int index, protobuf.usernet.Token.Builder builderForValue) {
      if (tokensBuilder_ == null) {
        ensureTokensIsMutable();
        tokens_.add(index, builderForValue.build());
        onChanged();
      } else {
        tokensBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder addAllTokens(
        java.lang.Iterable<? extends protobuf.usernet.Token> values) {
      if (tokensBuilder_ == null) {
        ensureTokensIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tokens_);
        onChanged();
      } else {
        tokensBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder clearTokens() {
      if (tokensBuilder_ == null) {
        tokens_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        tokensBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public Builder removeTokens(int index) {
      if (tokensBuilder_ == null) {
        ensureTokensIsMutable();
        tokens_.remove(index);
        onChanged();
      } else {
        tokensBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public protobuf.usernet.Token.Builder getTokensBuilder(
        int index) {
      return getTokensFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public protobuf.usernet.TokenOrBuilder getTokensOrBuilder(
        int index) {
      if (tokensBuilder_ == null) {
        return tokens_.get(index);  } else {
        return tokensBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public java.util.List<? extends protobuf.usernet.TokenOrBuilder> 
         getTokensOrBuilderList() {
      if (tokensBuilder_ != null) {
        return tokensBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tokens_);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public protobuf.usernet.Token.Builder addTokensBuilder() {
      return getTokensFieldBuilder().addBuilder(
          protobuf.usernet.Token.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public protobuf.usernet.Token.Builder addTokensBuilder(
        int index) {
      return getTokensFieldBuilder().addBuilder(
          index, protobuf.usernet.Token.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.Token tokens = 8;</code>
     */
    public java.util.List<protobuf.usernet.Token.Builder> 
         getTokensBuilderList() {
      return getTokensFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.Token, protobuf.usernet.Token.Builder, protobuf.usernet.TokenOrBuilder> 
        getTokensFieldBuilder() {
      if (tokensBuilder_ == null) {
        tokensBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usernet.Token, protobuf.usernet.Token.Builder, protobuf.usernet.TokenOrBuilder>(
                tokens_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        tokens_ = null;
      }
      return tokensBuilder_;
    }

    private java.util.List<protobuf.usernet.InitialMarking> initialMarking_ =
      java.util.Collections.emptyList();
    private void ensureInitialMarkingIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        initialMarking_ = new java.util.ArrayList<protobuf.usernet.InitialMarking>(initialMarking_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.InitialMarking, protobuf.usernet.InitialMarking.Builder, protobuf.usernet.InitialMarkingOrBuilder> initialMarkingBuilder_;

    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public java.util.List<protobuf.usernet.InitialMarking> getInitialMarkingList() {
      if (initialMarkingBuilder_ == null) {
        return java.util.Collections.unmodifiableList(initialMarking_);
      } else {
        return initialMarkingBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public int getInitialMarkingCount() {
      if (initialMarkingBuilder_ == null) {
        return initialMarking_.size();
      } else {
        return initialMarkingBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public protobuf.usernet.InitialMarking getInitialMarking(int index) {
      if (initialMarkingBuilder_ == null) {
        return initialMarking_.get(index);
      } else {
        return initialMarkingBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder setInitialMarking(
        int index, protobuf.usernet.InitialMarking value) {
      if (initialMarkingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInitialMarkingIsMutable();
        initialMarking_.set(index, value);
        onChanged();
      } else {
        initialMarkingBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder setInitialMarking(
        int index, protobuf.usernet.InitialMarking.Builder builderForValue) {
      if (initialMarkingBuilder_ == null) {
        ensureInitialMarkingIsMutable();
        initialMarking_.set(index, builderForValue.build());
        onChanged();
      } else {
        initialMarkingBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder addInitialMarking(protobuf.usernet.InitialMarking value) {
      if (initialMarkingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInitialMarkingIsMutable();
        initialMarking_.add(value);
        onChanged();
      } else {
        initialMarkingBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder addInitialMarking(
        int index, protobuf.usernet.InitialMarking value) {
      if (initialMarkingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInitialMarkingIsMutable();
        initialMarking_.add(index, value);
        onChanged();
      } else {
        initialMarkingBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder addInitialMarking(
        protobuf.usernet.InitialMarking.Builder builderForValue) {
      if (initialMarkingBuilder_ == null) {
        ensureInitialMarkingIsMutable();
        initialMarking_.add(builderForValue.build());
        onChanged();
      } else {
        initialMarkingBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder addInitialMarking(
        int index, protobuf.usernet.InitialMarking.Builder builderForValue) {
      if (initialMarkingBuilder_ == null) {
        ensureInitialMarkingIsMutable();
        initialMarking_.add(index, builderForValue.build());
        onChanged();
      } else {
        initialMarkingBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder addAllInitialMarking(
        java.lang.Iterable<? extends protobuf.usernet.InitialMarking> values) {
      if (initialMarkingBuilder_ == null) {
        ensureInitialMarkingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, initialMarking_);
        onChanged();
      } else {
        initialMarkingBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder clearInitialMarking() {
      if (initialMarkingBuilder_ == null) {
        initialMarking_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        initialMarkingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public Builder removeInitialMarking(int index) {
      if (initialMarkingBuilder_ == null) {
        ensureInitialMarkingIsMutable();
        initialMarking_.remove(index);
        onChanged();
      } else {
        initialMarkingBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public protobuf.usernet.InitialMarking.Builder getInitialMarkingBuilder(
        int index) {
      return getInitialMarkingFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public protobuf.usernet.InitialMarkingOrBuilder getInitialMarkingOrBuilder(
        int index) {
      if (initialMarkingBuilder_ == null) {
        return initialMarking_.get(index);  } else {
        return initialMarkingBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public java.util.List<? extends protobuf.usernet.InitialMarkingOrBuilder> 
         getInitialMarkingOrBuilderList() {
      if (initialMarkingBuilder_ != null) {
        return initialMarkingBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(initialMarking_);
      }
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public protobuf.usernet.InitialMarking.Builder addInitialMarkingBuilder() {
      return getInitialMarkingFieldBuilder().addBuilder(
          protobuf.usernet.InitialMarking.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public protobuf.usernet.InitialMarking.Builder addInitialMarkingBuilder(
        int index) {
      return getInitialMarkingFieldBuilder().addBuilder(
          index, protobuf.usernet.InitialMarking.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 9;</code>
     */
    public java.util.List<protobuf.usernet.InitialMarking.Builder> 
         getInitialMarkingBuilderList() {
      return getInitialMarkingFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.usernet.InitialMarking, protobuf.usernet.InitialMarking.Builder, protobuf.usernet.InitialMarkingOrBuilder> 
        getInitialMarkingFieldBuilder() {
      if (initialMarkingBuilder_ == null) {
        initialMarkingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.usernet.InitialMarking, protobuf.usernet.InitialMarking.Builder, protobuf.usernet.InitialMarkingOrBuilder>(
                initialMarking_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        initialMarking_ = null;
      }
      return initialMarkingBuilder_;
    }

    private long threshold_ ;
    /**
     * <code>int64 threshold = 10;</code>
     * @return Whether the threshold field is set.
     */
    @java.lang.Override
    public boolean hasThreshold() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>int64 threshold = 10;</code>
     * @return The threshold.
     */
    @java.lang.Override
    public long getThreshold() {
      return threshold_;
    }
    /**
     * <code>int64 threshold = 10;</code>
     * @param value The threshold to set.
     * @return This builder for chaining.
     */
    public Builder setThreshold(long value) {
      bitField0_ |= 0x00000040;
      threshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 threshold = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreshold() {
      bitField0_ = (bitField0_ & ~0x00000040);
      threshold_ = 0L;
      onChanged();
      return this;
    }

    private long intervalDuration_ ;
    /**
     * <code>int64 intervalDuration = 11;</code>
     * @return Whether the intervalDuration field is set.
     */
    @java.lang.Override
    public boolean hasIntervalDuration() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>int64 intervalDuration = 11;</code>
     * @return The intervalDuration.
     */
    @java.lang.Override
    public long getIntervalDuration() {
      return intervalDuration_;
    }
    /**
     * <code>int64 intervalDuration = 11;</code>
     * @param value The intervalDuration to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalDuration(long value) {
      bitField0_ |= 0x00000080;
      intervalDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 intervalDuration = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntervalDuration() {
      bitField0_ = (bitField0_ & ~0x00000080);
      intervalDuration_ = 0L;
      onChanged();
      return this;
    }

    private long distanceBetweenIntervals_ ;
    /**
     * <code>int64 distanceBetweenIntervals = 12;</code>
     * @return Whether the distanceBetweenIntervals field is set.
     */
    @java.lang.Override
    public boolean hasDistanceBetweenIntervals() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>int64 distanceBetweenIntervals = 12;</code>
     * @return The distanceBetweenIntervals.
     */
    @java.lang.Override
    public long getDistanceBetweenIntervals() {
      return distanceBetweenIntervals_;
    }
    /**
     * <code>int64 distanceBetweenIntervals = 12;</code>
     * @param value The distanceBetweenIntervals to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceBetweenIntervals(long value) {
      bitField0_ |= 0x00000100;
      distanceBetweenIntervals_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 distanceBetweenIntervals = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistanceBetweenIntervals() {
      bitField0_ = (bitField0_ & ~0x00000100);
      distanceBetweenIntervals_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.usernet.AgentNet)
  }

  // @@protoc_insertion_point(class_scope:protobuf.usernet.AgentNet)
  private static final protobuf.usernet.AgentNet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.usernet.AgentNet();
  }

  public static protobuf.usernet.AgentNet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentNet>
      PARSER = new com.google.protobuf.AbstractParser<AgentNet>() {
    @java.lang.Override
    public AgentNet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AgentNet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AgentNet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentNet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.usernet.AgentNet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

