// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserNet.proto

package protobuf.usernet;

public interface TokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.usernet.Token)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string agentNet = 3;</code>
   * @return Whether the agentNet field is set.
   */
  boolean hasAgentNet();
  /**
   * <code>string agentNet = 3;</code>
   * @return The agentNet.
   */
  java.lang.String getAgentNet();
  /**
   * <code>string agentNet = 3;</code>
   * @return The bytes for agentNet.
   */
  com.google.protobuf.ByteString
      getAgentNetBytes();

  /**
   * <code>.protobuf.usernet.Color color = 4;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.protobuf.usernet.Color color = 4;</code>
   * @return The color.
   */
  protobuf.usernet.Color getColor();
  /**
   * <code>.protobuf.usernet.Color color = 4;</code>
   */
  protobuf.usernet.ColorOrBuilder getColorOrBuilder();
}
