// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserNet.proto

package protobuf.usernet;

public interface UserNetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.usernet.UserNet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .protobuf.usernet.Place places = 3;</code>
   */
  java.util.List<protobuf.usernet.Place> 
      getPlacesList();
  /**
   * <code>repeated .protobuf.usernet.Place places = 3;</code>
   */
  protobuf.usernet.Place getPlaces(int index);
  /**
   * <code>repeated .protobuf.usernet.Place places = 3;</code>
   */
  int getPlacesCount();
  /**
   * <code>repeated .protobuf.usernet.Place places = 3;</code>
   */
  java.util.List<? extends protobuf.usernet.PlaceOrBuilder> 
      getPlacesOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.Place places = 3;</code>
   */
  protobuf.usernet.PlaceOrBuilder getPlacesOrBuilder(
      int index);

  /**
   * <code>string startPlaceId = 4;</code>
   * @return The startPlaceId.
   */
  java.lang.String getStartPlaceId();
  /**
   * <code>string startPlaceId = 4;</code>
   * @return The bytes for startPlaceId.
   */
  com.google.protobuf.ByteString
      getStartPlaceIdBytes();

  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 5;</code>
   */
  java.util.List<protobuf.usernet.Transition> 
      getTransitionsList();
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 5;</code>
   */
  protobuf.usernet.Transition getTransitions(int index);
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 5;</code>
   */
  int getTransitionsCount();
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 5;</code>
   */
  java.util.List<? extends protobuf.usernet.TransitionOrBuilder> 
      getTransitionsOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.Transition transitions = 5;</code>
   */
  protobuf.usernet.TransitionOrBuilder getTransitionsOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 6;</code>
   */
  java.util.List<protobuf.usernet.Arc> 
      getArcsList();
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 6;</code>
   */
  protobuf.usernet.Arc getArcs(int index);
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 6;</code>
   */
  int getArcsCount();
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 6;</code>
   */
  java.util.List<? extends protobuf.usernet.ArcOrBuilder> 
      getArcsOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.Arc arcs = 6;</code>
   */
  protobuf.usernet.ArcOrBuilder getArcsOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usernet.Token tokens = 7;</code>
   */
  java.util.List<protobuf.usernet.Token> 
      getTokensList();
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 7;</code>
   */
  protobuf.usernet.Token getTokens(int index);
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 7;</code>
   */
  int getTokensCount();
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 7;</code>
   */
  java.util.List<? extends protobuf.usernet.TokenOrBuilder> 
      getTokensOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.Token tokens = 7;</code>
   */
  protobuf.usernet.TokenOrBuilder getTokensOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 8;</code>
   */
  java.util.List<protobuf.usernet.InitialMarking> 
      getInitialMarkingList();
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 8;</code>
   */
  protobuf.usernet.InitialMarking getInitialMarking(int index);
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 8;</code>
   */
  int getInitialMarkingCount();
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 8;</code>
   */
  java.util.List<? extends protobuf.usernet.InitialMarkingOrBuilder> 
      getInitialMarkingOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.InitialMarking initialMarking = 8;</code>
   */
  protobuf.usernet.InitialMarkingOrBuilder getInitialMarkingOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.usernet.AgentNet agentNets = 9;</code>
   */
  java.util.List<protobuf.usernet.AgentNet> 
      getAgentNetsList();
  /**
   * <code>repeated .protobuf.usernet.AgentNet agentNets = 9;</code>
   */
  protobuf.usernet.AgentNet getAgentNets(int index);
  /**
   * <code>repeated .protobuf.usernet.AgentNet agentNets = 9;</code>
   */
  int getAgentNetsCount();
  /**
   * <code>repeated .protobuf.usernet.AgentNet agentNets = 9;</code>
   */
  java.util.List<? extends protobuf.usernet.AgentNetOrBuilder> 
      getAgentNetsOrBuilderList();
  /**
   * <code>repeated .protobuf.usernet.AgentNet agentNets = 9;</code>
   */
  protobuf.usernet.AgentNetOrBuilder getAgentNetsOrBuilder(
      int index);
}
