// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserNet.proto

package protobuf.usernet;

public final class UserNetOuterClass {
  private UserNetOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_UserNet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_UserNet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_AgentNet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_AgentNet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_Place_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_Place_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_Transition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_Transition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_Arc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_Arc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_Token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_InitialMarking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_InitialMarking_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_usernet_Color_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_usernet_Color_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rUserNet.proto\022\020protobuf.usernet\"\332\002\n\007Us" +
      "erNet\022\n\n\002id\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022\'\n\006" +
      "places\030\003 \003(\0132\027.protobuf.usernet.Place\022\024\n" +
      "\014startPlaceId\030\004 \001(\t\0221\n\013transitions\030\005 \003(\013" +
      "2\034.protobuf.usernet.Transition\022#\n\004arcs\030\006" +
      " \003(\0132\025.protobuf.usernet.Arc\022\'\n\006tokens\030\007 " +
      "\003(\0132\027.protobuf.usernet.Token\0228\n\016initialM" +
      "arking\030\010 \003(\0132 .protobuf.usernet.InitialM" +
      "arking\022-\n\tagentNets\030\t \003(\0132\032.protobuf.use" +
      "rnet.AgentNetB\007\n\005_name\"\312\003\n\010AgentNet\022\n\n\002i" +
      "d\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022\024\n\014startPlace" +
      "Id\030\004 \001(\t\022\'\n\006places\030\005 \003(\0132\027.protobuf.user" +
      "net.Place\0221\n\013transitions\030\006 \003(\0132\034.protobu" +
      "f.usernet.Transition\022#\n\004arcs\030\007 \003(\0132\025.pro" +
      "tobuf.usernet.Arc\022\'\n\006tokens\030\010 \003(\0132\027.prot" +
      "obuf.usernet.Token\0228\n\016initialMarking\030\t \003" +
      "(\0132 .protobuf.usernet.InitialMarking\022\026\n\t" +
      "threshold\030\n \001(\003H\001\210\001\001\022\035\n\020intervalDuration" +
      "\030\013 \001(\003H\002\210\001\001\022%\n\030distanceBetweenIntervals\030" +
      "\014 \001(\003H\003\210\001\001B\007\n\005_nameB\014\n\n_thresholdB\023\n\021_in" +
      "tervalDurationB\033\n\031_distanceBetweenInterv" +
      "als\"[\n\005Place\022\n\n\002id\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000" +
      "\210\001\001\022\016\n\001x\030\003 \001(\001H\001\210\001\001\022\016\n\001y\030\004 \001(\001H\002\210\001\001B\007\n\005_" +
      "nameB\004\n\002_xB\004\n\002_y\"`\n\nTransition\022\n\n\002id\030\001 \001" +
      "(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022\016\n\001x\030\003 \001(\001H\001\210\001\001\022\016\n" +
      "\001y\030\004 \001(\001H\002\210\001\001B\007\n\005_nameB\004\n\002_xB\004\n\002_y\"Q\n\003Ar" +
      "c\022\n\n\002id\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022\020\n\010sour" +
      "ceId\030\003 \001(\t\022\020\n\010targetId\030\004 \001(\tB\007\n\005_name\"\212\001" +
      "\n\005Token\022\n\n\002id\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022\025" +
      "\n\010agentNet\030\003 \001(\tH\001\210\001\001\022+\n\005color\030\004 \001(\0132\027.p" +
      "rotobuf.usernet.ColorH\002\210\001\001B\007\n\005_nameB\013\n\t_" +
      "agentNetB\010\n\006_color\"2\n\016InitialMarking\022\017\n\007" +
      "tokenId\030\001 \001(\t\022\017\n\007placeId\030\002 \001(\t\"I\n\005Color\022" +
      "\016\n\001r\030\001 \001(\005H\000\210\001\001\022\016\n\001g\030\002 \001(\005H\001\210\001\001\022\016\n\001b\030\003 \001" +
      "(\005H\002\210\001\001B\004\n\002_rB\004\n\002_gB\004\n\002_bB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_usernet_UserNet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_usernet_UserNet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_UserNet_descriptor,
        new java.lang.String[] { "Id", "Name", "Places", "StartPlaceId", "Transitions", "Arcs", "Tokens", "InitialMarking", "AgentNets", "Name", });
    internal_static_protobuf_usernet_AgentNet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_usernet_AgentNet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_AgentNet_descriptor,
        new java.lang.String[] { "Id", "Name", "StartPlaceId", "Places", "Transitions", "Arcs", "Tokens", "InitialMarking", "Threshold", "IntervalDuration", "DistanceBetweenIntervals", "Name", "Threshold", "IntervalDuration", "DistanceBetweenIntervals", });
    internal_static_protobuf_usernet_Place_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_usernet_Place_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_Place_descriptor,
        new java.lang.String[] { "Id", "Name", "X", "Y", "Name", "X", "Y", });
    internal_static_protobuf_usernet_Transition_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protobuf_usernet_Transition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_Transition_descriptor,
        new java.lang.String[] { "Id", "Name", "X", "Y", "Name", "X", "Y", });
    internal_static_protobuf_usernet_Arc_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protobuf_usernet_Arc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_Arc_descriptor,
        new java.lang.String[] { "Id", "Name", "SourceId", "TargetId", "Name", });
    internal_static_protobuf_usernet_Token_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protobuf_usernet_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_Token_descriptor,
        new java.lang.String[] { "Id", "Name", "AgentNet", "Color", "Name", "AgentNet", "Color", });
    internal_static_protobuf_usernet_InitialMarking_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protobuf_usernet_InitialMarking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_InitialMarking_descriptor,
        new java.lang.String[] { "TokenId", "PlaceId", });
    internal_static_protobuf_usernet_Color_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protobuf_usernet_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_usernet_Color_descriptor,
        new java.lang.String[] { "R", "G", "B", "R", "G", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
